spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888


server:
  port: 8100
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 30
management:
  endpoints:
    web:
      exposure:
        include: "*"