spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///home/monkey/git-localconfig-repo
        default-label: master
server:
  port: 8888
